### PR TITLE
fixes #159

### LINKED ISSUE #159: Other Copies Message Link Fails
The "more copies" link in the message contained in https://github.com/pulibrary/requests/blob/development/app/views/requests/request/_umlaut_services.html.erb#L132-L147 doesn't work. 

I think we need to rethink that is the or when an item is not borrow_direct_eligible?. This message only makes sense to display when a record has more than one holding. As this is currently this message this will show for every record that isn't in a borrow_direct_eligible? state regardless of how many holdings/copies are attached to that record.

### PR DESCRIPTION
**Pull request by sdellis**

### CODE REVIEW

**Comment by kevinreiss** [comment]
This currently addresses the issue of displaying the message when appropriate. However it doesn't fix the issue with the link being off-kilter when it is actually displayed.

**Comment by sdellis** [comment]
Not sure I understand. Can you clarify what you mean by "off-kilter"?

**Comment by kevinreiss** [comment]
See https://github.com/pulibrary/requests/blob/development/app/views/requests/request/_umlaut_services.html.erb#L136

I think if you are at a page that has a URL ending in:

```
/requests/1231414?mfhd=123144
```

You just get sent back there with the that current HTML code rather than going to:
```
/requests/1231414
```
Which is think is the intention here.

**Comment by sdellis** [comment]
No, my intention was to reveal the other available items on their current page. I'm not sure we talked about the other approach, though it would also work.

**Comment by kevinreiss** [comment]
Okay. I misunderstood.

**Comment by sdellis** [comment]
Assuming the user could be coming from anywhere, they end up on a Request form which may not allow them to request the item. This is most likely because there is an alternate holding on campus that is "available". Since they cannot request the item, this PR allows them to view their other options for obtaining the item. Linking them to the un-scoped record would also solve the problem, but since we already have all the desired information in this context, I figured we could just display it and not require a full page reload (along with all the redundant requests to other systems).

**Comment by kevinreiss** [comment]
As I understand this issue this message will be invoked in cases when we have a charged item at one holding but there is a lendable copy at another holding. If the user has visited the form with the mfhd parameter included the other mfhd data isn't part of the page as things currently stand. How is it going to be displayed?

**Comment by sdellis** [comment]
No, I refactored it so that the mfhd data is part of the page when the item is not a serial. This was addressed in [this PR](https://github.com/pulibrary/requests/pull/144). The other holdings are just hidden so that the view is consistent with the expectations of being able to "scope" with a mfhd parameter. 

Are holdings not getting displayed for you when you test this locally and click the link to show other available copies?

**Comment by kevinreiss** [comment]
No, I haven't tested this. I didn't realize the change with multiple holdings for non-serials had been made.

**Pull request merged**
