### PR TITLE
Adding recap to the list of libraries that is open

### PR DESCRIPTION
**Pull request by carolyncole**
There is still one failing test, but I am not sure what a recap no items one should really look like...
Screen Shot 2020-06-04 at 3 09 01 PM

### CODE REVIEW

**Comment by kevinreiss** [comment]
recap_no_items would be treated as one of the "fill-in" options we looked earlier. It generates an email to recapproblems the staff follow up manually with.

**Comment by carolyncole** [comment]
@kevinreiss so the pickup location should not selectable, it should be just Firestone, and there should be only the one option that goes to  recapproblems not the two options above?

**Comment by kevinreiss** [comment]
In this case the item is for use only in Firestone library in normal operating times.

**Comment by carolyncole** [comment]
@kevinreiss 
Recap no items record
Screen Shot 2020-06-05 at 8 33 45 AM
Regular recap record
Screen Shot 2020-06-05 at 8 35 39 AM

**Pull request merged**
