### PR TITLE
Removes Copy 0, fixes #i986

### PR DESCRIPTION
**Pull request by sdellis**

### CODE REVIEW

**Review by kevinreiss — CHANGES_REQUESTED** [review]
Looks good, but you could add a spec to test this?

**Comment by sdellis** [comment]
@kevinreiss this should be ready for review.

**Review by kevinreiss — COMMENTED** [review]
Could this be checked with an item that has other enumeration and the "copy 0"? This is an example:

/requests/99120673453506421?mfhd=2282155380006421&source=pulsearch

I think fact that always returning the empty string when copy 0 is present without considering the case of other enumeration might suppress info you'd otherwise want to display from the the other enum/chron fields.

**Comment by sdellis** [comment]
@kevinreiss I somehow broke another test while fixing this one, but I wanted to check in sooner than later and make sure this is what you are looking for.

**Comment by sdellis** [comment]
@kevinreiss this looks ready to merge!

**Review by kevinreiss — APPROVED** [review]

**Pull request merged**
